SELECT *
FROM Person.Person;

SELECT COUNT(*)
FROM Person.Person;

SELECT COUNT(Title)
FROM Person.Person;

SELECT COUNT(DISTINCT Title)
FROM Person.Person;

/*
DESAFIO #1
EU QUERO SABER  QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS (Production.Product)
*/
SELECT *
FROM Production.Product;

SELECT COUNT(ProductID)
FROM Production.Product;

SELECT COUNT(DISTINCT ProductID)
FROM Production.Product;

/*
DESAFIO #2
EU QUERO SABER QUANTOS TAMANHOS  DE PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA
*/
SELECT COUNT(Size)
FROM Production.Product;

/*
DESAFIO #3
EU QUERO SABER QUANTOS TAMANHOS DIFERENTES  DE PRODUTOS  EU TENHO CADASTRADOS EM NOSSA TABELA 
*/
SELECT COUNT(DISTINCT Size)
FROM Production.Product;